//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18033
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ME3Patch.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ME3Patch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] bgm1 {
            get {
                object obj = ResourceManager.GetObject("bgm1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] bgm2 {
            get {
                object obj = ResourceManager.GetObject("bgm2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] BIOGame_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("BIOGame_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] BIOGame_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("BIOGame_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] BIOGame_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("BIOGame_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM10 {
            get {
                object obj = ResourceManager.GetObject("Data_COM10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM11 {
            get {
                object obj = ResourceManager.GetObject("Data_COM11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM12 {
            get {
                object obj = ResourceManager.GetObject("Data_COM12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM13 {
            get {
                object obj = ResourceManager.GetObject("Data_COM13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM14 {
            get {
                object obj = ResourceManager.GetObject("Data_COM14", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM15 {
            get {
                object obj = ResourceManager.GetObject("Data_COM15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM16 {
            get {
                object obj = ResourceManager.GetObject("Data_COM16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM17 {
            get {
                object obj = ResourceManager.GetObject("Data_COM17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM18 {
            get {
                object obj = ResourceManager.GetObject("Data_COM18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM19 {
            get {
                object obj = ResourceManager.GetObject("Data_COM19", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM2 {
            get {
                object obj = ResourceManager.GetObject("Data_COM2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM20 {
            get {
                object obj = ResourceManager.GetObject("Data_COM20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM3 {
            get {
                object obj = ResourceManager.GetObject("Data_COM3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM4 {
            get {
                object obj = ResourceManager.GetObject("Data_COM4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM5 {
            get {
                object obj = ResourceManager.GetObject("Data_COM5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM6 {
            get {
                object obj = ResourceManager.GetObject("Data_COM6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM7 {
            get {
                object obj = ResourceManager.GetObject("Data_COM7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM8 {
            get {
                object obj = ResourceManager.GetObject("Data_COM8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Data_COM9 {
            get {
                object obj = ResourceManager.GetObject("Data_COM9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_APP01_INT_COM {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_APP01_INT_COM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_APP01_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_APP01_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_DH1_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_DH1_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_DH1_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_DH1_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_DH1_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_DH1_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_END_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_END_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_END_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_END_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_END_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_END_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_GUN01_INT_COM {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_GUN01_INT_COM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_GUN01_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_GUN01_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_GUN02_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_GUN02_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_GUN02_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_GUN02_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_GUN02_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_GUN02_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_MP1_INT_COM {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_MP1_INT_COM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_MP1_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_MP1_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_MP2_INT_COM {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_MP2_INT_COM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_MP2_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_MP2_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_MP3_INT_COM {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_MP3_INT_COM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_MP3_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_MP3_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_MP4_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_MP4_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_MP4_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_MP4_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_MP4_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_MP4_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_MP5_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_MP5_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_MP5_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_MP5_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_CON_MP5_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_CON_MP5_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_EXP_Pack001_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("DLC_EXP_Pack001_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_EXP_Pack001_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("DLC_EXP_Pack001_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_EXP_Pack001_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_EXP_Pack001_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_EXP_Pack002_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("DLC_EXP_Pack002_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_EXP_Pack002_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("DLC_EXP_Pack002_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_EXP_Pack002_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_EXP_Pack002_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_EXP_Pack003_Base_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("DLC_EXP_Pack003_Base_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_EXP_Pack003_Base_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("DLC_EXP_Pack003_Base_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_EXP_Pack003_Base_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_EXP_Pack003_Base_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_EXP_Pack003_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("DLC_EXP_Pack003_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_EXP_Pack003_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("DLC_EXP_Pack003_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_EXP_Pack003_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_EXP_Pack003_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_HEN_PR_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("DLC_HEN_PR_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_HEN_PR_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("DLC_HEN_PR_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_HEN_PR_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_HEN_PR_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHE10 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHE10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHE11 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHE11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHE12 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHE12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHE13 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHE13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHE15 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHE15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHE16 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHE16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHE17 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHE17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHE18 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHE18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHE19 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHE19", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHE20 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHE20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHE6 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHE6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHE7 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHE7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHN10 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHN10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHN11 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHN11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHN12 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHN12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHN13 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHN13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHN15 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHN15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHN16 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHN16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHN17 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHN17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHN18 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHN18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHN19 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHN19", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHN20 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHN20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_CHN7 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_CHN7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_COM6 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_COM6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_COM8 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_COM8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_COM9 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_COM9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG10 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG11 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG12 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG13 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG15 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG16 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG17 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG18 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG19 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG19", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG20 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG6 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG7 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG8 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_Shared_INT_ENG9 {
            get {
                object obj = ResourceManager.GetObject("DLC_Shared_INT_ENG9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_UPD_Patch01_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("DLC_UPD_Patch01_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_UPD_Patch01_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("DLC_UPD_Patch01_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_UPD_Patch01_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_UPD_Patch01_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_UPD_Patch02_INT_CHE {
            get {
                object obj = ResourceManager.GetObject("DLC_UPD_Patch02_INT_CHE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_UPD_Patch02_INT_CHN {
            get {
                object obj = ResourceManager.GetObject("DLC_UPD_Patch02_INT_CHN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_UPD_Patch02_INT_ENG {
            get {
                object obj = ResourceManager.GetObject("DLC_UPD_Patch02_INT_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Icon_15 {
            get {
                object obj = ResourceManager.GetObject("Icon_15", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] MassEffect3Config_ENG {
            get {
                object obj = ResourceManager.GetObject("MassEffect3Config_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] MassEffect3Config_ENG1 {
            get {
                object obj = ResourceManager.GetObject("MassEffect3Config_ENG1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SFXGUI_Fonts_COM {
            get {
                object obj = ResourceManager.GetObject("SFXGUI_Fonts_COM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SFXGUI_Fonts_DLC_COM {
            get {
                object obj = ResourceManager.GetObject("SFXGUI_Fonts_DLC_COM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SFXGUI_Fonts_DLC_ENG {
            get {
                object obj = ResourceManager.GetObject("SFXGUI_Fonts_DLC_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SFXGUI_Fonts_ENG {
            get {
                object obj = ResourceManager.GetObject("SFXGUI_Fonts_ENG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 金敬姬 {
            get {
                object obj = ResourceManager.GetObject("金敬姬", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
